version: '0.1'
services:
  grpc:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./entrypoint-grpc.sh
    ports:
      - 50051:50051
    depends_on:
      - postgres
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./entrypoint-api.sh
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - grpc
  postgres:
    image: postgres:14
    # restart: always
    environment:
        POSTGRES_PASSWORD: 'postgres'
        POSTGRES_USER: 'postgres'
        POSTGRES_DB: 'testdb'  # Add this line
    volumes:
        - ./postgres:/var/lib/postgresql/data
        - ./init:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432