# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: blog_proto/post.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x62log_proto/post.proto\x12\x04post\x1a\x1bgoogle/protobuf/empty.proto\"2\n\x04Post\x12\n\n\x02id\x18\x01 \x01(\x03\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\"\x11\n\x0fPostListRequest\"!\n\x13PostRetrieveRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x32\xed\x01\n\x0ePostController\x12-\n\x04List\x12\x15.post.PostListRequest\x1a\n.post.Post\"\x00\x30\x01\x12\"\n\x06\x43reate\x12\n.post.Post\x1a\n.post.Post\"\x00\x12\x33\n\x08Retrieve\x12\x19.post.PostRetrieveRequest\x1a\n.post.Post\"\x00\x12\"\n\x06Update\x12\n.post.Post\x1a\n.post.Post\"\x00\x12/\n\x07\x44\x65stroy\x12\n.post.Post\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'blog_proto.post_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _POST._serialized_start=60
  _POST._serialized_end=110
  _POSTLISTREQUEST._serialized_start=112
  _POSTLISTREQUEST._serialized_end=129
  _POSTRETRIEVEREQUEST._serialized_start=131
  _POSTRETRIEVEREQUEST._serialized_end=164
  _POSTCONTROLLER._serialized_start=167
  _POSTCONTROLLER._serialized_end=404
# @@protoc_insertion_point(module_scope)
