# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from upload_proto import upload_pb2 as upload__proto_dot_upload__pb2


class UploadServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadFiles = channel.unary_unary(
                '/monitor.UploadService/UploadFiles',
                request_serializer=upload__proto_dot_upload__pb2.UploadRequest.SerializeToString,
                response_deserializer=upload__proto_dot_upload__pb2.UploadResponse.FromString,
                )


class UploadServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UploadFiles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UploadServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadFiles,
                    request_deserializer=upload__proto_dot_upload__pb2.UploadRequest.FromString,
                    response_serializer=upload__proto_dot_upload__pb2.UploadResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'monitor.UploadService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class UploadService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UploadFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/monitor.UploadService/UploadFiles',
            upload__proto_dot_upload__pb2.UploadRequest.SerializeToString,
            upload__proto_dot_upload__pb2.UploadResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
