# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: upload_proto/upload.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19upload_proto/upload.proto\x12\x07monitor\"&\n\x04\x46ile\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"-\n\rUploadRequest\x12\x1c\n\x05\x66iles\x18\x01 \x03(\x0b\x32\r.monitor.File\"!\n\x0eUploadResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32O\n\rUploadService\x12>\n\x0bUploadFiles\x12\x16.monitor.UploadRequest\x1a\x17.monitor.UploadResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'upload_proto.upload_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FILE._serialized_start=38
  _FILE._serialized_end=76
  _UPLOADREQUEST._serialized_start=78
  _UPLOADREQUEST._serialized_end=123
  _UPLOADRESPONSE._serialized_start=125
  _UPLOADRESPONSE._serialized_end=158
  _UPLOADSERVICE._serialized_start=160
  _UPLOADSERVICE._serialized_end=239
# @@protoc_insertion_point(module_scope)
